add venue support for telegram alarm
pokealarm/pokealarm pull request #768
Opened 2021-04-09 13:09 UTC by AstAst42

## Description
Adds possibility to use venues in telegram alarms. Venues are very similar to maps, but they can have additional text just below the text. This makes it easier to understand which "map" (venue) message belongs to which mon text message and makes it easier to share the alarm by simply sharing the venue only. You can edit the venue text like all other texts but keep in mind that the space is limited.

![image](https://user-images.githubusercontent.com/34718776/114180342-5fd9d480-9940-11eb-95af-52877f489796.png)

This text is also shown after pressing on the venue if you want to use navigation.

![image](https://user-images.githubusercontent.com/34718776/114180925-2e153d80-9941-11eb-800a-080c96cdd23b.png)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context

This makes it easier to find the Mons you are looking for because you can combine mon values with a map and improves sharing.

## How Has This Been Tested?

I used this as a local change on a server for 3 small cities, had it run for months and had no problems.

## Wiki Update

- [x] This change requires an update to the Wiki.
- [ ] This change does not require an update to the Wiki.

2021-05-07 19:33 UTC, LegitDongo commented
This seems like it would cause unexpected results for those who use current message functionality with the venue option on

Can someone confirm that this works as expected even without the venue message option?

2022-02-01 01:24 UTC, billyjbryant commented on PokeAlarm/Alarms/Telegram/TelegramAlarm.py
> +            'venue_message': "",
Wouldn't the proper thing here be to set `venue_message` to `null` rather than an empty string?

2022-02-01 01:26 UTC, billyjbryant commented
Is it possible to disable this in settings so that Venues show only if they are either enabled or not disabled?

2022-02-10 18:23 UTC, billyjbryant requested changes
Please address the comments on this PR

2022-03-24 19:20 UTC, billyjbryant commented
This PR appears to be abandoned, please re-open and address comments if you wish to introduce this feature.

2022-03-24 19:20 UTC, closed without merging