Hisui update
pokealarm/pokealarm pull request #787
Opened 2022-01-30 13:36 UTC by Audidriver13

## Description

Update of new Hisui Voltorb form

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

2022-01-31 23:28 UTC, billyjbryant commented
Code change looks good but https://monsterimages.tk/regular/monsters/100_2728.png does not resolve and instead reverts to 100_000.png. Looks like the base images haven't been updated yet.

2022-01-31 23:29 UTC, billyjbryant approved these changes

2022-01-31 23:32 UTC, billyjbryant requested changes
This change needs to be introduced into all Locales at one time. Please include translations for `ko`, `pt` and `zh_hk` as wel.

2022-02-01 09:19 UTC, Audidriver13 commented
> This change needs to be introduced into all Locales at one time. Please include translations for `ko`, `pt` and `zh_hk` as wel.

Updated the remaining languages, but not in local language (ko and zh_hk). But it was often used that way.

2022-02-02 08:39 UTC, billyjbryant approved these changes

2022-02-02 08:39 UTC, merged