Add new moves portuguese translation
pokealarm/pokealarm pull request #800
Opened 2022-02-12 14:52 UTC by lzibeti

## Description

Add new moves portuguese translation and add move "lock-on".
## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context

The "lock-on" move always appeared as unknown and looking at the files I saw that it was missing. I took the moment to update the file in Portuguese, updating with the new moves.

## How Has This Been Tested?

Translation is being used on my server, in production environment, sending information to 2 Telegram groups without error.
## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

2022-02-12 21:05 UTC, billyjbryant requested changes

2022-02-12 21:05 UTC, billyjbryant commented on locales/pt.json
> +    "281": "Poder Oculto",
Please fix spacing for all entries below this one to ensure uniformity of the file.

2022-02-12 23:59 UTC, lzibeti commented on locales/pt.json
> +    "281": "Poder Oculto",
Sorry, I didn't know it generated this difference using notepad++. I'll fix it.

2022-02-13 00:05 UTC, lzibeti commented on locales/pt.json
> +    "281": "Poder Oculto",
Done

2022-02-14 22:53 UTC, billyjbryant approved these changes

2022-02-14 22:56 UTC, merged