Added virtualenv doc and updated scanner doc
pokealarm/pokealarm pull request #814
Opened 2022-03-02 23:24 UTC by Pontiky

## Description

This PR adds the `virtualenv` doc to isolate PokeAlarm environment from other Python projects.
I also removed all the references to outdated scanners/tools (Monocle and Rocketmap) and added the new ones (MAD and RDM) with some links and tips to configure them correctly with PA.
I finally changed python commands to `python3` and `pip3` as otherwise it might refer to Python 2 for installations with both Python.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context

This will close #715.

## How Has This Been Tested?

No test needed

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [ ] This change does not require an update to the Wiki.
- [x] This change is a Wiki update.

2022-03-07 16:02 UTC, LegitDongo requested changes
TIL that default python in newest ubuntu is `python3`, along with `pip3`

I would have assumed that it would still default to `python` and `pip`, but this isn't the case, these commands are not available (I'm guessing since 2.7 isn't there)


Got a few small typos

2022-03-07 16:02 UTC, LegitDongo commented on docs/configuration/geofences.rst
> +rescrit work movement, but PA uses them to restrict events. As a result,
typo

2022-03-07 16:02 UTC, LegitDongo commented on docs/getting-started/installation.rst
> +   logging informations about what it is doing to the console.
`information` was correct

2022-03-07 19:16 UTC, Pontiky commented
> TIL that default python in newest ubuntu is `python3`, along with `pip3`
> 
> I would have assumed that it would still default to `python` and `pip`, but this isn't the case, these commands are not available (I'm guessing since 2.7 isn't there)

That's it but if you are using `virtualenv` by specifying python3 at creation, you can use both `pip` and `pip3` in this env as the first one will be an alias of the second one.

2022-03-09 15:21 UTC, LegitDongo approved these changes
LGTM

2022-03-09 15:21 UTC, merged