Add support of Python 3.9 and 3.10
pokealarm/pokealarm pull request #844
Opened 2022-07-07 18:39 UTC by Pontiky

## Description

Add Python 3.9 and 3.10 support

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (would cause existing functionality to change)

**PLEASE UPGRADE YOUR PACKAGES AFTER THIS COMMIT:**
`pip install -r  requirements.txt --upgrade`

## Motivation and Context

Python 3.10 is shipped as a default with Ubuntu 22.04.
Python 3.9 is also very common now.
Closes #838

## How Has This Been Tested?

Tested using a fresh config of Python 3.9.5 and Python 3.10.5
Python 3.7 and 3.8 are still supported with the package upgrades.

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

2022-07-07 23:35 UTC, billyjbryant requested changes

2022-07-07 23:35 UTC, billyjbryant commented on start_pokealarm.py
>      log.info("PokeAlarm is closing down!")
maybe add a debug log entry here as to which SigNum we are responding to since we have it available now.

2022-07-08 17:44 UTC, Pontiky commented on start_pokealarm.py
>      log.info("PokeAlarm is closing down!")
Good idea, done!

2022-07-09 09:18 UTC, billyjbryant approved these changes

2022-07-09 09:18 UTC, merged